### ISSUE TITLE
OpenTelekomCloud as Provider is required

### ISSUE THREAD

**Issue by Moep90** [mattray/inspec-iggy#22]
hey there,

this seams like a nice project!
I would love to see this work for more terraform provider!

I'm currently working with OpenTelekomCloud. (https://www.terraform.io/docs/providers/opentelekomcloud/index.html)
and It would be nice to have it working too.

Best regards and keep it up!

**Comment by mattray** [comment]
Does InSpec support OpenTelekomCloud? If there's not a plugin supporting it Iggy won't be able to generate any coverage. It maps from the Terraform resources to the InSpec resources, so both tools need to support the platform. What happens when you currently run against the .tfstate files?

I'm including a DESIGN.md doc to assist in supporting new platforms with the upcoming release.
